import { StyleSheet } from 'react-native';
import { colors, spacing } from '@/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, width: '100%' },
  flex: { flex: 1, width: '100%' },
  scroll: { flex: 1, width: '100%' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
  },
  brandIcon: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  brandText: { fontSize: 10, fontWeight: '700' },
  brandName: { fontSize: 16, fontWeight: '700' },
  content: {
    paddingHorizontal: 32,
    paddingBottom: 16,
    flexGrow: 1,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  hero: { alignItems: 'center', marginBottom: 28, paddingTop: 8 },
  logoCircle: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  logo: { width: 80, height: 80 },
  welcome: { fontSize: 24, fontWeight: '700', marginBottom: 8, textAlign: 'center' },
  welcomeSub: { fontSize: 14, textAlign: 'center', lineHeight: 20 },
  fieldGap: { height: 16 },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginVertical: 16,
  },
  forgot: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  forgotText: { fontSize: 14, fontWeight: '500' },
  loginError: {
    color: colors.error,
    fontSize: 12,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  footer: {
    paddingHorizontal: 32,
    paddingBottom: 20,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
  dividerRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 16 },
  divider: { flex: 1, height: 1 },
  dividerText: { paddingHorizontal: 12, fontSize: 10, letterSpacing: 2, fontWeight: '700' },
  contact: { textAlign: 'center', fontSize: 14 },
  accentBar: { height: 4, width: '100%', opacity: 0.6 },
  formBody: {
    paddingHorizontal: 32,
    paddingTop: 8,
    paddingBottom: 24,
    flexGrow: 1,
    width: '100%',
    maxWidth: 480,
    alignSelf: 'center',
  },
});
