import { Alert, Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { stitchImages } from '@/assets/images';
import { SCHOOL_NAME } from '@/constants/school';

export interface AttendanceReportRow {
  class: string;
  present: number;
  absent: number;
  rate: number;
}

export interface AttendanceReportInput {
  title: string;
  dateLabel: string;
  summary: { present: number; absent: number; late: number; leave: number; rate: string };
  rows: AttendanceReportRow[];
  rangeLabel?: string;
}

function sanitizeFilename(title: string): string {
  const base = title
    .trim()
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '_')
    .slice(0, 80);
  return base.endsWith('.pdf') ? base : `${base || 'Attendance_Report'}.pdf`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildAttendanceHtml(input: AttendanceReportInput): string {
  const { title, dateLabel, summary, rows, rangeLabel } = input;
  const rowHtml = rows
    .map(
      (r) =>
        `<tr>
          <td>${escapeHtml(r.class)}</td>
          <td style="text-align:center">${r.present}</td>
          <td style="text-align:center">${r.absent}</td>
          <td style="text-align:center;font-weight:600">${r.rate}%</td>
        </tr>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { margin: 24mm 20mm; }
    body { font-family: Helvetica, Arial, sans-serif; color: #1a1a1a; margin: 0; line-height: 1.5; }
    .header { display: flex; align-items: center; gap: 16px; border-bottom: 2px solid #0fbd83; padding-bottom: 16px; margin-bottom: 20px; }
    .logo { width: 56px; height: 56px; object-fit: contain; }
    .school { font-size: 18px; font-weight: 700; color: #0f766e; }
    .meta { font-size: 12px; color: #64748b; margin-top: 4px; }
    h1 { font-size: 20px; margin: 0 0 8px; }
    .summary { display: flex; gap: 24px; margin: 16px 0 24px; flex-wrap: wrap; }
    .stat { min-width: 90px; }
    .stat-lbl { font-size: 11px; color: #64748b; text-transform: uppercase; }
    .stat-val { font-size: 22px; font-weight: 700; color: #0f766e; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { background: #ecfdf5; text-align: left; padding: 10px 8px; font-size: 11px; text-transform: uppercase; }
    td { padding: 10px 8px; border-bottom: 1px solid #e2e8f0; }
    .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <img class="logo" src="${stitchImages.loginLogo}" alt="School logo" />
    <div>
      <div class="school">${escapeHtml(SCHOOL_NAME)}</div>
      <div class="meta">${escapeHtml(dateLabel)}${rangeLabel ? ` · ${escapeHtml(rangeLabel)}` : ''}</div>
    </div>
  </div>
  <h1>${escapeHtml(title)}</h1>
  <div class="summary">
    <div class="stat"><div class="stat-lbl">Present</div><div class="stat-val">${summary.present}</div></div>
    <div class="stat"><div class="stat-lbl">Absent</div><div class="stat-val">${summary.absent}</div></div>
    <div class="stat"><div class="stat-lbl">Late</div><div class="stat-val">${summary.late}</div></div>
    <div class="stat"><div class="stat-lbl">Leave</div><div class="stat-val">${summary.leave}</div></div>
    <div class="stat"><div class="stat-lbl">Rate</div><div class="stat-val">${escapeHtml(summary.rate)}</div></div>
  </div>
  <table>
    <thead>
      <tr>
        <th>Class</th>
        <th style="text-align:center">Present</th>
        <th style="text-align:center">Absent</th>
        <th style="text-align:center">Rate</th>
      </tr>
    </thead>
    <tbody>${rowHtml}</tbody>
  </table>
  <div class="footer">Generated by Principal ERP · ${escapeHtml(new Date().toLocaleString('en-IN'))}</div>
</body>
</html>`;
}

async function sharePdfWeb(html: string, filename: string, title: string): Promise<void> {
  const printWin = window.open('', '_blank');
  if (!printWin) {
    Alert.alert('Download failed', 'Please allow pop-ups to export the report as PDF.');
    return;
  }
  printWin.document.write(html);
  printWin.document.title = filename.replace(/\.pdf$/i, '');
  printWin.document.close();
  printWin.focus();
  setTimeout(() => printWin.print(), 400);
  Alert.alert('Save as PDF', `"${title}" is ready. Choose "Save as PDF" in the print dialog.`);
}

async function sharePdfNative(html: string, filename: string, title: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  const dest = `${FileSystem.cacheDirectory}${filename}`;
  await FileSystem.copyAsync({ from: uri, to: dest });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(dest, {
      mimeType: 'application/pdf',
      dialogTitle: title,
      UTI: 'com.adobe.pdf',
    });
    return;
  }

  Alert.alert('PDF ready', `Report saved as ${filename}`);
}

export async function shareAttendanceReportAsPdf(input: AttendanceReportInput): Promise<void> {
  const html = buildAttendanceHtml(input);
  const filename = sanitizeFilename(input.title);

  try {
    if (Platform.OS === 'web') {
      await sharePdfWeb(html, filename, input.title);
      return;
    }
    await sharePdfNative(html, filename, input.title);
  } catch {
    Alert.alert('Download failed', 'Could not generate the attendance report. Please try again.');
  }
}
