import { Alert, Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { stitchImages } from '@/assets/images';
import { SCHOOL_NAME } from '@/constants/school';

export interface CircularPdfInput {
  title: string;
  body: string;
  circularNo: string;
  audience?: string;
  date?: string;
}

function sanitizeFilename(title: string): string {
  const base = title
    .trim()
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '_')
    .slice(0, 80);
  return base.endsWith('.pdf') ? base : `${base || 'Circular'}.pdf`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function buildCircularHtml(input: CircularPdfInput): string {
  const { title, body, circularNo, audience, date } = input;
  const metaParts = [date, audience].filter(Boolean).join(' · ');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { margin: 28mm 22mm; }
    body {
      font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
      color: #1a1a1a;
      margin: 0;
      padding: 0;
      line-height: 1.55;
    }
    .header {
      text-align: center;
      border-bottom: 2px solid #1e3a5f;
      padding-bottom: 18px;
      margin-bottom: 24px;
    }
    .logo {
      width: 72px;
      height: 72px;
      object-fit: contain;
      margin-bottom: 10px;
    }
    .school-name {
      font-size: 20px;
      font-weight: 700;
      color: #1e3a5f;
      margin: 0 0 6px;
    }
    .circular-no {
      font-size: 12px;
      color: #555;
      letter-spacing: 0.5px;
      margin: 0;
    }
    .title {
      font-size: 18px;
      font-weight: 700;
      margin: 0 0 8px;
      color: #111;
    }
    .meta {
      font-size: 12px;
      color: #666;
      margin-bottom: 20px;
    }
    .body {
      font-size: 14px;
      white-space: pre-wrap;
      text-align: justify;
    }
    .footer {
      margin-top: 36px;
      font-size: 11px;
      color: #888;
      text-align: center;
      border-top: 1px solid #ddd;
      padding-top: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <img class="logo" src="${stitchImages.loginLogo}" alt="School logo" />
    <p class="school-name">${escapeHtml(SCHOOL_NAME)}</p>
    <p class="circular-no">Circular No. ${escapeHtml(circularNo)}</p>
  </div>
  <h1 class="title">${escapeHtml(title)}</h1>
  ${metaParts ? `<p class="meta">${escapeHtml(metaParts)}</p>` : ''}
  <div class="body">${escapeHtml(body)}</div>
  <p class="footer">Generated by ${escapeHtml(SCHOOL_NAME)} · Official Circular</p>
</body>
</html>`;
}

async function sharePdfWeb(html: string, filename: string, title: string): Promise<void> {
  const printWin = window.open('', '_blank');
  if (!printWin) {
    Alert.alert('Share failed', 'Please allow pop-ups to export the circular as PDF.');
    return;
  }
  printWin.document.write(html);
  printWin.document.title = filename.replace(/\.pdf$/i, '');
  printWin.document.close();
  printWin.focus();
  setTimeout(() => {
    printWin.print();
  }, 400);
  Alert.alert('Save as PDF', `"${title}" is ready. Choose "Save as PDF" in the print dialog. The file will use the circular title as its name.`);
}

async function sharePdfNative(html: string, filename: string, title: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  const dest = `${FileSystem.cacheDirectory}${filename}`;
  await FileSystem.copyAsync({ from: uri, to: dest });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(dest, {
      mimeType: 'application/pdf',
      dialogTitle: title,
      UTI: 'com.adobe.pdf',
    });
    return;
  }

  Alert.alert('PDF ready', `Circular saved as ${filename}`);
}

export async function shareCircularAsPdf(input: CircularPdfInput): Promise<void> {
  const html = buildCircularHtml(input);
  const filename = sanitizeFilename(input.title);

  try {
    if (Platform.OS === 'web') {
      await sharePdfWeb(html, filename, input.title);
      return;
    }
    await sharePdfNative(html, filename, input.title);
  } catch {
    Alert.alert('Share failed', 'Could not generate the circular PDF. Please try again.');
  }
}

export function nextCircularNumber(existing: { circularNo: string }[]): string {
  const year = new Date().getFullYear();
  const prefix = `CIR/${year}/`;
  const max = existing.reduce((acc, item) => {
    const match = item.circularNo.match(/CIR\/\d{4}\/(\d+)/);
    const num = match ? parseInt(match[1], 10) : 0;
    return Math.max(acc, num);
  }, 0);
  return `${prefix}${String(max + 1).padStart(4, '0')}`;
}
