import { MaterialIcons } from '@expo/vector-icons';

/** Maps Stitch Material Symbol names to Expo MaterialIcons */
export const symbolToIcon: Record<string, keyof typeof MaterialIcons.glyphMap> = {
  arrow_back: 'arrow-back',
  notifications: 'notifications',
  calendar_today: 'calendar-today',
  menu_book: 'menu-book',
  person_check: 'how-to-reg',
  chevron_right: 'chevron-right',
  expand_more: 'keyboard-arrow-down',
  expand_less: 'keyboard-arrow-up',
  campaign: 'campaign',
  home: 'home',
  dashboard: 'dashboard',
  calendar_month: 'calendar-month',
  groups: 'groups',
  assignment: 'assignment',
  person: 'person',
  badge: 'badge',
  lock: 'lock',
  visibility: 'visibility',
  visibility_off: 'visibility-off',
  login: 'login',
  security: 'security',
  dark_mode: 'dark-mode',
  light_mode: 'light-mode',
  school: 'school',
  target: 'gps-fixed',
  fact_check: 'fact-check',
  grade: 'grade',
  mail: 'mail',
  chat: 'chat',
  add: 'add',
  edit: 'edit',
  search: 'search',
  filter_list: 'filter-list',
  send: 'send',
  attach_file: 'attach-file',
  call: 'call',
  more_vert: 'more-vert',
  check: 'check',
  close: 'close',
  schedule: 'schedule',
  checklist: 'checklist',
  edit_note: 'edit-note',
  download: 'download',
  wifi_off: 'wifi-off',
  logout: 'logout',
  language: 'language',
  privacy_tip: 'privacy-tip',
  undo: 'undo',
  check_circle: 'check-circle',
  cancel: 'cancel',
  access_time: 'access-time',
  sync: 'sync',
  wc: 'wc',
  cake: 'cake',
  work: 'work',
  subject: 'subject',
  photo_camera: 'photo-camera',
  swipe: 'swipe',
  chat_bubble_outline: 'chat-bubble-outline',
  rotate_left: 'rotate-left',
  wifi: 'wifi',
  event_busy: 'event-busy',
  payments: 'payments',
  leaderboard: 'leaderboard',
  warning: 'warning',
  info: 'info',
  settings: 'settings',
};

export function getIcon(name: string): keyof typeof MaterialIcons.glyphMap {
  return symbolToIcon[name] ?? 'help-outline';
}
