import { Alert, Platform } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { stitchImages } from '@/assets/images';
import { SCHOOL_NAME } from '@/constants/school';
import { formatMonthYear } from '@/utils/datetime';

export interface ReportMetric {
  label: string;
  value: string;
}

export interface ReportTableSection {
  heading: string;
  columns: string[];
  rows: string[][];
}

export interface SchoolReportInput {
  title: string;
  periodLabel?: string;
  summary?: string;
  metrics?: ReportMetric[];
  tables?: ReportTableSection[];
}

export function buildReportFilename(title: string, period = formatMonthYear()): string {
  const periodToken = period.replace(/\s+/g, '_');
  const titleToken = title
    .trim()
    .replace(/[<>:"/\\|?*]/g, '')
    .replace(/\s+/g, '_')
    .slice(0, 60);
  return `IDPS_${titleToken}_${periodToken}.pdf`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildReportHtml(input: SchoolReportInput): string {
  const { title, periodLabel, summary, metrics, tables } = input;
  const period = periodLabel ?? formatMonthYear();

  const metricBlock = metrics?.length
    ? `<div class="summary">
        ${metrics
          .map(
            (m) =>
              `<div class="stat"><div class="stat-lbl">${escapeHtml(m.label)}</div><div class="stat-val">${escapeHtml(m.value)}</div></div>`,
          )
          .join('')}
       </div>`
    : '';

  const summaryBlock = summary ? `<p class="summary-text">${escapeHtml(summary)}</p>` : '';

  const tableBlocks =
    tables
      ?.map((table) => {
        const head = table.columns.map((c) => `<th>${escapeHtml(c)}</th>`).join('');
        const body = table.rows
          .map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`)
          .join('');
        return `<h2>${escapeHtml(table.heading)}</h2>
                <table><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
      })
      .join('') ?? '';

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { margin: 24mm 20mm; }
    body { font-family: Helvetica, Arial, sans-serif; color: #1a1a1a; margin: 0; line-height: 1.5; }
    .header { display: flex; align-items: center; gap: 16px; border-bottom: 2px solid #0fbd83; padding-bottom: 16px; margin-bottom: 20px; }
    .logo { width: 56px; height: 56px; object-fit: contain; }
    .school { font-size: 18px; font-weight: 700; color: #0f766e; }
    .meta { font-size: 12px; color: #64748b; margin-top: 4px; }
    h1 { font-size: 20px; margin: 0 0 8px; color: #0f766e; }
    h2 { font-size: 14px; margin: 24px 0 8px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; }
    .summary { display: flex; gap: 20px; margin: 16px 0 20px; flex-wrap: wrap; }
    .stat { min-width: 120px; }
    .stat-lbl { font-size: 11px; color: #64748b; text-transform: uppercase; }
    .stat-val { font-size: 20px; font-weight: 700; color: #0f766e; }
    .summary-text { font-size: 14px; color: #475569; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 16px; }
    th { background: #ecfdf5; text-align: left; padding: 10px 8px; font-size: 11px; text-transform: uppercase; }
    td { padding: 10px 8px; border-bottom: 1px solid #e2e8f0; }
    .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; }
  </style>
</head>
<body>
  <div class="header">
    <img class="logo" src="${stitchImages.loginLogo}" alt="IDPS logo" />
    <div>
      <div class="school">${escapeHtml(SCHOOL_NAME)}</div>
      <div class="meta">${escapeHtml(period)} · Principal Reports &amp; Analytics</div>
    </div>
  </div>
  <h1>${escapeHtml(title)}</h1>
  ${summaryBlock}
  ${metricBlock}
  ${tableBlocks}
  <div class="footer">Generated by IDPS Principal ERP · ${escapeHtml(new Date().toLocaleString('en-IN'))}</div>
</body>
</html>`;
}

async function sharePdfWeb(html: string, filename: string, title: string): Promise<void> {
  const printWin = window.open('', '_blank');
  if (!printWin) {
    Alert.alert('Download failed', 'Please allow pop-ups to export the report as PDF.');
    return;
  }
  printWin.document.write(html);
  printWin.document.title = filename.replace(/\.pdf$/i, '');
  printWin.document.close();
  printWin.focus();
  setTimeout(() => printWin.print(), 400);
  Alert.alert('Save as PDF', `"${title}" is ready. Save as ${filename} from the print dialog.`);
}

async function sharePdfNative(html: string, filename: string, title: string): Promise<void> {
  const { uri } = await Print.printToFileAsync({ html });
  const dest = `${FileSystem.cacheDirectory}${filename}`;
  await FileSystem.copyAsync({ from: uri, to: dest });

  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(dest, {
      mimeType: 'application/pdf',
      dialogTitle: title,
      UTI: 'com.adobe.pdf',
    });
    return;
  }

  Alert.alert('PDF ready', `Report saved as ${filename}`);
}

export async function shareSchoolReportAsPdf(input: SchoolReportInput, filename?: string): Promise<void> {
  const html = buildReportHtml(input);
  const file = filename ?? buildReportFilename(input.title, input.periodLabel);

  try {
    if (Platform.OS === 'web') {
      await sharePdfWeb(html, file, input.title);
      return;
    }
    await sharePdfNative(html, file, input.title);
  } catch {
    Alert.alert('Download failed', 'Could not generate the report PDF. Please try again.');
  }
}
