import { StyleSheet } from 'react-native';
import { colors, spacing } from '@/theme';
import { cardShadow } from '@/utils/cardShadow';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  scroll: {
    flexGrow: 1,
  },
  summaryBand: {
    paddingHorizontal: spacing.md,
    paddingTop: 14,
    paddingBottom: 12,
    backgroundColor: colors.canvas,
    gap: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'center',
    gap: 6,
  },
  summaryChip: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minWidth: 0,
    paddingHorizontal: 8,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: colors.slate200,
  },
  summaryChipText: {
    flex: 1,
    minWidth: 0,
    fontSize: 11,
    fontWeight: '700',
    color: colors.primary,
  },
  progressBlock: {
    gap: 8,
  },
  progressHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  progressLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.slate500,
  },
  progressPercent: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.primary,
  },
  progressTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.slate200,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: colors.primary,
  },
  content: {
    paddingHorizontal: spacing.md,
    gap: spacing.md,
  },
  statsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  statCard: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 4,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    ...cardShadow,
  },
  statValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.slate900,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.slate500,
    marginTop: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  presentValue: { color: colors.primary },
  absentValue: { color: colors.error },
  lateValue: { color: '#d97706' },
  hintCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    backgroundColor: `${colors.primary}08`,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: `${colors.primary}22`,
  },
  hintTextBlock: {
    flex: 1,
    gap: 2,
  },
  hintTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: colors.slate900,
  },
  hintText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.slate500,
  },
  reviewLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    paddingVertical: 8,
  },
  reviewLinkText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.primary,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: spacing.md,
    paddingTop: 12,
    backgroundColor: colors.canvas,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.slate200,
  },
  submitBtn: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: 'center',
    ...cardShadow,
  },
  submitText: {
    color: colors.onPrimary,
    fontWeight: '800',
    fontSize: 15,
  },
});
