import { StyleSheet } from 'react-native';
import { borderRadius, colors, shadows, spacing } from '@/theme';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  scroll: { paddingBottom: 160 },
  scrollDone: { paddingBottom: 120 },
  content: { paddingHorizontal: spacing.md },
  chips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
  },
  chip: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.full,
    backgroundColor: `${colors.primaryContainer}1A`,
    borderWidth: 1,
    borderColor: `${colors.primaryContainer}33`,
  },
  chipText: { color: colors.primaryContainer },
  summary: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    marginTop: spacing.sm,
    borderWidth: 1,
    borderColor: colors.slate100,
    ...shadows.sm,
  },
  summaryCell: { flex: 1, alignItems: 'center' },
  summaryValue: { fontWeight: '700' },
  summaryLabel: { color: colors.outline, marginTop: 2 },
  summaryDivider: {
    width: 1,
    height: 32,
    backgroundColor: colors.slate100,
  },
  presentValue: { color: colors.primaryContainer },
  absentValue: { color: colors.absent },
  lateValue: { color: colors.late },
  hint: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    marginTop: spacing.md,
    marginBottom: spacing.sm,
  },
  hintText: { color: colors.outline },
  progress: {
    textAlign: 'center',
    color: colors.onSurfaceVariant,
    marginBottom: spacing.sm,
    fontWeight: '600',
  },
  deckWrap: {
    marginTop: spacing.sm,
  },
  footer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 80,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    backgroundColor: colors.background,
  },
  submitBtn: {
    backgroundColor: colors.primaryContainer,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.xl,
    alignItems: 'center',
    ...shadows.md,
  },
  submitText: { color: colors.onPrimary, fontWeight: '700' },
  listBtn: {
    marginTop: spacing.sm,
    alignItems: 'center',
    paddingVertical: spacing.sm,
  },
  listBtnDone: {
    marginTop: 0,
  },
  listBtnText: { color: colors.primaryContainer, fontWeight: '600' },
});
