import { StyleSheet } from 'react-native';
import { borderRadius, colors, spacing } from '@/theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.canvas,
    maxWidth: spacing.maxWidth,
    width: '100%',
    alignSelf: 'center',
  },
  decorTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: 128,
    height: 128,
    borderBottomRightRadius: borderRadius.full,
    backgroundColor: `${colors.primary}0d`,
  },
  decorBottom: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 192,
    height: 192,
    borderTopLeftRadius: borderRadius.full,
    backgroundColor: `${colors.primary}0d`,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    gap: spacing.xl,
  },
  logoRing: {
    width: 192,
    height: 192,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 4,
    borderColor: `${colors.primary}33`,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
  },
  logo: { width: '100%', height: '100%' },
  branding: { alignItems: 'center', gap: spacing.md },
  title: { color: colors.slate900, fontSize: 36, fontWeight: '700', letterSpacing: -0.5 },
  taglineRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  tagline: { color: colors.slate500, fontSize: 18, fontWeight: '500' },
  school: { color: colors.primary, letterSpacing: 3, fontSize: 10, fontWeight: '600' },
  progressSection: {
    width: '100%',
    maxWidth: 320,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  progressLabelRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  progressLabel: { color: colors.slate900, fontSize: 14, fontWeight: '500' },
  progressPct: { color: colors.primary, fontSize: 14, fontWeight: '700' },
  progressTrack: {
    height: 12,
    backgroundColor: `${colors.primary}1a`,
    borderRadius: borderRadius.full,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: `${colors.primary}1a`,
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.primary,
    borderRadius: borderRadius.full,
  },
  footer: { paddingBottom: spacing.xl, alignItems: 'center' },
  version: { color: colors.slate500, fontSize: 10, letterSpacing: 3 },
});
