import { StyleSheet } from 'react-native';
import { borderRadius, colors, spacing } from '@/theme';

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.canvas,
    maxWidth: spacing.maxWidth,
    width: '100%',
    alignSelf: 'center',
  },
  decorTop: {
    position: 'absolute',
    top: -96,
    left: -96,
    width: 256,
    height: 256,
    borderRadius: borderRadius.full,
    backgroundColor: `${colors.primaryContainer}0D`,
  },
  decorBottom: {
    position: 'absolute',
    bottom: -96,
    right: -96,
    width: 256,
    height: 256,
    borderRadius: borderRadius.full,
    backgroundColor: `${colors.secondaryContainer}0D`,
  },
  center: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
    gap: spacing.xl,
  },
  logoRing: {
    width: 192,
    height: 192,
    borderRadius: borderRadius.full,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 6,
    borderColor: `${colors.primaryContainer}33`,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: { width: 128, height: 128 },
  branding: { alignItems: 'center', gap: spacing.md },
  title: { color: colors.slate900 },
  taglineRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  tagline: { color: colors.slate500 },
  school: { color: colors.primaryContainer, letterSpacing: 3.2 },
  progressSection: {
    width: '100%',
    maxWidth: 320,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xl,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.sm,
  },
  progressLabelRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  progressLabel: { color: colors.slate500 },
  progressPct: { color: colors.primaryContainer },
  progressTrack: {
    height: 12,
    backgroundColor: `${colors.primaryContainer}1A`,
    borderRadius: borderRadius.full,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: colors.primaryContainer,
    borderRadius: borderRadius.full,
  },
  footer: { paddingBottom: spacing.xl, alignItems: 'center' },
  version: { color: colors.slate500 },
});
