-- Seed IDPS departments and designations for all branches (idempotent)
-- Generated by scripts/generate-departments-seed-migration.mjs

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
dept_seed (slug, name, category) AS (
  VALUES
  ('teaching-support', 'TEACHING SUPPORT', 'teaching'),
  ('robotics', 'ROBOTICS', 'teaching'),
  ('space', 'SPACE', 'teaching'),
  ('test', 'TEST', 'teaching'),
  ('academic-administration', 'ACADEMIC ADMINISTRATION', 'non_teaching'),
  ('teaching', 'TEACHING', 'teaching'),
  ('mess', 'MESS', 'non_teaching'),
  ('transportation', 'TRANSPORTATION', 'non_teaching'),
  ('management', 'MANAGEMENT', 'non_teaching'),
  ('cleaning', 'CLEANING', 'non_teaching'),
  ('non-teaching', 'NON TEACHING', 'non_teaching'),
  ('security', 'SECURITY', 'non_teaching'),
  ('computer', 'COMPUTER', 'non_teaching'),
  ('recruitment', 'RECRUITMENT', 'non_teaching'),
  ('site-and-engineering', 'SITE AND ENGINEERING', 'non_teaching'),
  ('finance-and-accounts', 'FINANCE AND ACCOUNTS', 'non_teaching'),
  ('books-and-uniforms', 'BOOKS AND UNIFORMS', 'non_teaching'),
  ('fee', 'FEE', 'non_teaching'),
  ('hostel', 'HOSTEL', 'non_teaching'),
  ('certificates', 'CERTIFICATES', 'non_teaching'),
  ('games-and-activities', 'GAMES AND ACTIVITIES', 'non_teaching'),
  ('medical', 'MEDICAL', 'non_teaching'),
  ('hod-teaching', 'HOD TEACHING', 'teaching'),
  ('incharge', 'INCHARGE', 'non_teaching'),
  ('school-app', 'SCHOOL APP', 'non_teaching')
),
upserted_departments AS (
  INSERT INTO public.departments (branch_id, slug, name, category, status)
  SELECT b.branch_id, d.slug, d.name, d.category, 'Active'
  FROM branch_targets b
  CROSS JOIN dept_seed d
  ON CONFLICT (branch_id, slug) DO UPDATE SET
    name = EXCLUDED.name,
    category = EXCLUDED.category,
    status = 'Active',
    updated_at = NOW()
  RETURNING id, branch_id, slug
)
SELECT 1;

-- Designations (per department slug, all branches)
WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('teaching-support', 'assistant-teacher', 'ASSISTANT TEACHER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('robotics', 'robotics-faculty', 'ROBOTICS FACULTY')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('space', 'space-faculty', 'SPACE FACULTY')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('test', 'test', 'TEST')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('academic-administration', 'academic-director', 'ACADEMIC DIRECTOR'),
  ('academic-administration', 'manager', 'MANAGER'),
  ('academic-administration', 'principal', 'PRINCIPAL'),
  ('academic-administration', 'vice-principal', 'VICE-PRINCIPAL')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('teaching', 'biology', 'BIOLOGY'),
  ('teaching', 'computer', 'COMPUTER'),
  ('teaching', 'english', 'ENGLISH'),
  ('teaching', 'french', 'FRENCH'),
  ('teaching', 'hindi', 'HINDI'),
  ('teaching', 'mathematics', 'MATHEMATICS'),
  ('teaching', 'mother-teacher', 'MOTHER TEACHER'),
  ('teaching', 'music-teacher', 'MUSIC TEACHER'),
  ('teaching', 'pgt-biology', 'PGT BIOLOGY'),
  ('teaching', 'pgt-chemistry', 'PGT CHEMISTRY'),
  ('teaching', 'pgt-computer', 'PGT COMPUTER'),
  ('teaching', 'pgt-english', 'PGT ENGLISH'),
  ('teaching', 'pgt-hindi', 'PGT HINDI'),
  ('teaching', 'pgt-mathematics', 'PGT MATHEMATICS'),
  ('teaching', 'pgt-physics', 'PGT PHYSICS'),
  ('teaching', 'pgt-science', 'PGT SCIENCE'),
  ('teaching', 'pgt-social-studies', 'PGT SOCIAL STUDIES'),
  ('teaching', 'pgt-telugu', 'PGT TELUGU'),
  ('teaching', 'phonics', 'PHONICS'),
  ('teaching', 'physics', 'PHYSICS'),
  ('teaching', 'pre-political-science', 'PRE POLITICAL SCIENCE'),
  ('teaching', 'prt-biology', 'PRT BIOLOGY'),
  ('teaching', 'prt-chemistry', 'PRT CHEMISTRY'),
  ('teaching', 'prt-computer', 'PRT COMPUTER'),
  ('teaching', 'prt-english', 'PRT ENGLISH'),
  ('teaching', 'prt-hindi', 'PRT HINDI'),
  ('teaching', 'prt-mathematics', 'PRT MATHEMATICS'),
  ('teaching', 'prt-science', 'PRT SCIENCE'),
  ('teaching', 'prt-social-studies', 'PRT SOCIAL STUDIES'),
  ('teaching', 'prt-telugu', 'PRT TELUGU'),
  ('teaching', 'robotics', 'ROBOTICS'),
  ('teaching', 'science', 'SCIENCE'),
  ('teaching', 'social-studies', 'SOCIAL STUDIES'),
  ('teaching', 'space-lab', 'SPACE LAB'),
  ('teaching', 'telugu', 'TELUGU'),
  ('teaching', 'tgt-biology', 'TGT BIOLOGY'),
  ('teaching', 'tgt-chemistry', 'TGT CHEMISTRY'),
  ('teaching', 'tgt-computer', 'TGT COMPUTER'),
  ('teaching', 'tgt-english', 'TGT ENGLISH'),
  ('teaching', 'tgt-hindi', 'TGT HINDI'),
  ('teaching', 'tgt-mathematics', 'TGT MATHEMATICS'),
  ('teaching', 'tgt-science', 'TGT SCIENCE'),
  ('teaching', 'tgt-social-studies', 'TGT SOCIAL STUDIES'),
  ('teaching', 'tgt-telugu', 'TGT TELUGU')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('mess', 'comm-i', 'COMM-I'),
  ('mess', 'comm-ii', 'COMM-II'),
  ('mess', 'helper', 'HELPER'),
  ('mess', 'mess-incharge', 'MESS INCHARGE'),
  ('mess', 'store-incharge', 'STORE INCHARGE')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('transportation', 'bus-ayya', 'BUS AYYA'),
  ('transportation', 'buses-incharge', 'BUSES INCHARGE'),
  ('transportation', 'conductor', 'CONDUCTOR'),
  ('transportation', 'driver', 'DRIVER'),
  ('transportation', 'sir-driver', 'SIR DRIVER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('management', 'ceo', 'CEO'),
  ('management', 'director', 'DIRECTOR'),
  ('management', 'founder', 'FOUNDER'),
  ('management', 'manager', 'MANAGER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('cleaning', 'aaya', 'AAYA'),
  ('cleaning', 'care-taker', 'CARE TAKER'),
  ('cleaning', 'cleaning-incharge', 'CLEANING INCHARGE'),
  ('cleaning', 'house-keeper', 'HOUSE KEEPER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('non-teaching', 'assistant-librarian', 'ASSISTANT LIBRARIAN'),
  ('non-teaching', 'clerk', 'CLERK'),
  ('non-teaching', 'librarian', 'LIBRARIAN'),
  ('non-teaching', 'receptionist', 'RECEPTIONIST')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('security', 'security-guard', 'SECURITY GUARD'),
  ('security', 'security-officer', 'SECURITY OFFICER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('computer', 'computer-operator', 'COMPUTER OPERATOR'),
  ('computer', 'network-admin', 'NETWORK ADMIN')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('recruitment', 'director-of-recruitment', 'DIRECTOR OF RECRUITMENT'),
  ('recruitment', 'h-r-manager', 'H R MANAGER'),
  ('recruitment', 'lead-recruiter', 'LEAD RECRUITER'),
  ('recruitment', 'recruitment-manager', 'RECRUITMENT MANAGER'),
  ('recruitment', 'technical-recruiter', 'TECHNICAL RECRUITER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('site-and-engineering', 'ac-mechanic', 'AC MECHANIC'),
  ('site-and-engineering', 'electrician', 'ELECTRICIAN'),
  ('site-and-engineering', 'engineer', 'ENGINEER'),
  ('site-and-engineering', 'loan-processing', 'LOAN PROCESSING'),
  ('site-and-engineering', 'mechanic', 'MECHANIC'),
  ('site-and-engineering', 'plumber', 'PLUMBER'),
  ('site-and-engineering', 'site-engineer', 'SITE ENGINEER')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('finance-and-accounts', 'accountant', 'ACCOUNTANT'),
  ('finance-and-accounts', 'finance-and-administration', 'FINANCE AND ADMINISTRATION')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('books-and-uniforms', 'books-incharge', 'BOOKS INCHARGE'),
  ('books-and-uniforms', 'uniforms', 'UNIFORMS')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('fee', 'fee-collection', 'FEE COLLECTION')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('hostel', 'hostel-incharge', 'HOSTEL INCHARGE')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('certificates', 'certificates-incharge', 'CERTIFICATES INCHARGE')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('games-and-activities', 'art-craft', 'ART & CRAFT'),
  ('games-and-activities', 'dance', 'DANCE'),
  ('games-and-activities', 'horse-riding-trainer', 'HORSE RIDING TRAINER'),
  ('games-and-activities', 'music', 'MUSIC'),
  ('games-and-activities', 'pet', 'PET'),
  ('games-and-activities', 'physical-director', 'PHYSICAL DIRECTOR'),
  ('games-and-activities', 'swimming-trainer', 'SWIMMING TRAINER'),
  ('games-and-activities', 'yoga', 'YOGA')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('medical', 'medical-compounder', 'MEDICAL COMPOUNDER'),
  ('medical', 'staff-nurse', 'STAFF NURSE')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('hod-teaching', 'hod-biology', 'HOD BIOLOGY'),
  ('hod-teaching', 'hod-english', 'HOD ENGLISH'),
  ('hod-teaching', 'hod-hindi', 'HOD HINDI'),
  ('hod-teaching', 'hod-mathematics', 'HOD MATHEMATICS'),
  ('hod-teaching', 'hod-social', 'HOD SOCIAL'),
  ('hod-teaching', 'hod-telugu', 'HOD TELUGU')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('incharge', 'first-floor-incharge', 'FIRST FLOOR INCHARGE'),
  ('incharge', 'ground-floor-incharge', 'GROUND FLOOR INCHARGE'),
  ('incharge', 'second-floor-incharge', 'SECOND FLOOR INCHARGE'),
  ('incharge', 'third-floor-incharge', 'THIRD FLOOR INCHARGE')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();

WITH branch_targets AS (
  SELECT id AS branch_id
  FROM public.branches
  WHERE slug IN ('idpscherukupalli', 'idpskalaburagi')
),
desig_seed (dept_slug, slug, name) AS (
  VALUES
  ('school-app', 'app-support', 'APP SUPPORT')
)
INSERT INTO public.designations (branch_id, department_id, slug, name, status)
SELECT b.branch_id, d.id, s.slug, s.name, 'Active'
FROM branch_targets b
JOIN public.departments d ON d.branch_id = b.branch_id
JOIN desig_seed s ON s.dept_slug = d.slug
ON CONFLICT (department_id, slug) DO UPDATE SET
  name = EXCLUDED.name,
  status = 'Active',
  updated_at = NOW();
