import { teacherBrand } from './brand';

/** IDPS palette — aligned with student app (#144835 green, #a2c144 accent) */
export const colors = {
  surface: '#f8f9ff',
  surfaceDim: '#cbdbf5',
  surfaceBright: '#f8f9ff',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerLow: '#eff4ff',
  surfaceContainer: '#e5eeff',
  surfaceContainerHigh: '#dce9ff',
  surfaceContainerHighest: '#d3e4fe',
  onSurface: '#0b1c30',
  onSurfaceVariant: '#3c4a42',
  inverseSurface: '#213145',
  inverseOnSurface: '#eaf1ff',
  outline: '#6c7a71',
  outlineVariant: '#bbcabf',
  surfaceTint: '#006c49',
  primary: teacherBrand.navy,
  onPrimary: '#ffffff',
  primaryContainer: teacherBrand.amber,
  onPrimaryContainer: teacherBrand.navy,
  inversePrimary: teacherBrand.amber,
  secondary: '#0058be',
  onSecondary: '#ffffff',
  secondaryContainer: '#2170e4',
  onSecondaryContainer: '#fefcff',
  tertiary: '#b91a24',
  onTertiary: '#ffffff',
  tertiaryContainer: '#ff8079',
  onTertiaryContainer: '#7e000f',
  error: '#ba1a1a',
  onError: '#ffffff',
  errorContainer: '#ffdad6',
  onErrorContainer: '#93000a',
  primaryFixed: '#6cfcbc',
  primaryFixedDim: '#4adfa2',
  onPrimaryFixed: '#002113',
  onPrimaryFixedVariant: '#005236',
  secondaryFixed: '#d8e2ff',
  secondaryFixedDim: '#adc6ff',
  onSecondaryFixed: '#001a42',
  onSecondaryFixedVariant: '#004395',
  tertiaryFixed: '#ffdad7',
  tertiaryFixedDim: '#ffb3ad',
  onTertiaryFixed: '#410004',
  onTertiaryFixedVariant: '#930013',
  background: teacherBrand.canvas,
  onBackground: '#0b1c30',
  surfaceVariant: '#d3e4fe',
  canvas: teacherBrand.canvas,
  accent: teacherBrand.amber,
  accentLight: teacherBrand.amberLight,
  primaryLight: teacherBrand.navyLight,
  absent: '#ef4444',
  late: '#f97316',
  presentBg: '#f0fdf4',
  absentBg: '#fef2f2',
  lateBg: '#fff7ed',
  slate100: '#f1f5f9',
  slate200: '#e2e8f0',
  slate400: '#94a3b8',
  slate500: '#64748b',
  slate900: '#0f172a',
  green500: '#22c55e',
  blue500: '#3b82f6',
  purple500: '#a855f7',
  orange500: '#f97316',
  amber500: '#f59e0b',
  stackCardDark: '#1a2c42',
  stackCardBorder: '#2d3e5a',
  heroGradientEnd: '#0ba370',
} as const;

export type ColorToken = keyof typeof colors;
