/** Timetable teacher labels → staff employee_id (2026-27). */
export const TIMETABLE_TEACHER_ALIASES: Record<string, string> = {
  "mr. anil": "anil",
  "ms. abinaya": "abinaya",
  "mr. aditya": "aditya",
  "mr. alok": "alok",
  "ms. asha": "asha",
  "ms. chhavi": "chhavi",
  "ms. flora": "flora",
  "ms. pinki singh": "pinki",
  "ms. ragini": "ragini",
  "ms. sabinya": "sabinya",
  "ms. sajima": "sajima",
  "ms. surajika": "surajika",
  "ms. tamanna": "tamanna",
  "mr. navin": "navin",
  "mr. praveen": "praveen",
  "ms. udhaya sree": "uday_sree",
  "mr. suresh purna": "suresh",
  "ms. satya": "sathya",
  "mr. saurabh": "sourabh",
  "mr. subhani": "subhani",
  "mr vishnu": "vishnu",
  "ms neha": "neha",
};
