import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { SCHOOL_LOGO_URI, SCHOOL_NAME } from '@/constants/config';
import type { MarksOverview, AcademicTerm } from '@/types';

const TERM_LABELS: Record<AcademicTerm, string> = {
  term1: 'Term 1',
  term2: 'Term 2',
  term3: 'Term 3',
  annual: 'Annual',
};

function sanitizeFilePart(value: string): string {
  return value.replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_|_$/g, '');
}

export function buildMarksPdfFileName(
  type: 'transcript' | 'report',
  studentName: string,
  term: AcademicTerm,
  className?: string,
): string {
  const docType = type === 'transcript' ? 'Academic_Transcript' : 'Report_Card';
  const name = sanitizeFilePart(studentName) || 'Student';
  const termLabel = sanitizeFilePart(TERM_LABELS[term]);
  const classPart = className ? `_${sanitizeFilePart(className)}` : '';
  const date = new Date().toISOString().slice(0, 10);
  return `IDPS_${docType}_${name}_${termLabel}${classPart}_${date}.pdf`;
}

interface MarksExportDetails {
  className?: string;
  studentId?: string;
}

function marksHtml(
  data: MarksOverview,
  term: AcademicTerm,
  studentName: string,
  title: string,
  details: MarksExportDetails = {},
) {
  const t = data.terms[term];
  const rows = t.subjects
    .map(
      (s) =>
        `<tr><td>${s.subject}</td><td>${s.score}/${s.maxScore}</td><td>${Math.round((s.score / s.maxScore) * 100)}%</td><td>${s.grade}</td></tr>`,
    )
    .join('');

  return `<!DOCTYPE html><html><head><style>
    body{font-family:Lexend,Arial,sans-serif;padding:32px;color:#0f172a}
    .header{display:flex;align-items:center;gap:16px;padding-bottom:16px;border-bottom:2px solid #0fbd83;margin-bottom:20px}
    .logo{width:72px;height:72px;object-fit:contain;border-radius:50%;border:2px solid #0fbd8333}
    .school-name{margin:0;font-size:20px;font-weight:800;color:#0f172a;line-height:1.3}
    .doc-type{margin:4px 0 0;font-size:13px;color:#0fbd83;font-weight:700;letter-spacing:1px;text-transform:uppercase}
    h1{color:#0fbd83;font-size:22px;margin:0 0 12px}
    table{width:100%;border-collapse:collapse;margin-top:16px}
    th,td{border:1px solid #e2e8f0;padding:10px;text-align:left}
    th{background:#f6f8f7}
    .summary{display:flex;flex-wrap:wrap;gap:16px;margin:16px 0}
    .box{background:#0fbd831a;padding:12px 16px;border-radius:8px;min-width:100px}
    .details{background:#f6f8f7;border-radius:8px;padding:16px;margin-bottom:8px}
    .details p{margin:6px 0;font-size:14px}
    .details strong{color:#475569}
  </style></head><body>
    <div class="header">
      <img class="logo" src="${SCHOOL_LOGO_URI}" alt="IDPS Logo" />
      <div>
        <h2 class="school-name">${SCHOOL_NAME}</h2>
        <p class="doc-type">${title}</p>
      </div>
    </div>
    <div class="details">
      <p><strong>Student:</strong> ${studentName}</p>
      ${details.studentId ? `<p><strong>Enrollment ID:</strong> ${details.studentId}</p>` : ''}
      ${details.className ? `<p><strong>Class:</strong> ${details.className}</p>` : ''}
      <p><strong>Term:</strong> ${TERM_LABELS[term]}</p>
      <p><strong>Teacher In Charge:</strong> ${data.teacherInCharge}</p>
      <p><strong>Last Updated:</strong> ${data.lastUpdated}</p>
    </div>
    <div class="summary">
      <div class="box"><div>GPA</div><strong>${t.gpa} / 4.0</strong></div>
      <div class="box"><div>Grade</div><strong>${t.grade}</strong></div>
      <div class="box"><div>Overall %</div><strong>${t.totalPercent}%</strong></div>
      <div class="box"><div>Rank</div><strong>${t.rank}</strong></div>
    </div>
    <table><thead><tr><th>Subject</th><th>Marks</th><th>%</th><th>Grade</th></tr></thead><tbody>${rows}</tbody></table>
    <p style="margin-top:32px;color:#64748b;font-size:12px">Generated by IDPS Student Portal</p>
  </body></html>`;
}

export async function exportMarksPdf(
  data: MarksOverview,
  term: AcademicTerm,
  studentName: string,
  type: 'transcript' | 'report',
  details: MarksExportDetails = {},
) {
  const title = type === 'transcript' ? 'Academic Transcript' : 'Report Card';
  const { uri } = await Print.printToFileAsync({ html: marksHtml(data, term, studentName, title, details) });
  return uri;
}

export async function shareMarksPdf(uri: string, title: string) {
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: title });
  }
}

export async function saveMarksPdf(uri: string, fileName: string) {
  const dest = `${FileSystem.documentDirectory ?? ''}${fileName}`;
  await FileSystem.copyAsync({ from: uri, to: dest });
  return dest;
}
